### ISSUE TITLE
Peer Feedback Sessie — 01

### ISSUE THREAD

**Issue by joordy** [lars-ruijs/web-app-from-scratch-2021#1]
# Rubric:

## App structure and code quality

> You can structure your code by applying patterns. You can substantiate the choice for the chosen patterns

- [x] The code contains no syntax errors and is neatly formatted
- [ ] Code is scoped correctly and divided into modules that correspond to the actor diagram.

### Tips

- No modules yet. Start with using a JS bundler! The advantage is that you can use node_modules, and split up your code in modules.. Perfect for the router that comes up in two weeks!

## Retrieve, manipulate and display data

> "You can retrieve data, manipulate it and convert it dynamically to html elements using templating.
You understand how to work with an external API using asynchronous code. "

- [x] JSON data can be retrieved from an API with an asynchronous request
- [x] JSON data is possible, at least with the methods; map, filter and reduce are manipulated
- [x] JSON data can be rendered client side in the HTML, with or without a micro library. Disadvantages of the client-side rendering of HTML can be mentioned

### Tips

- No filter and reduce yet, but map already there! 
- The data is appended to the HTML. Can the data be updated by the user? Or removed? Maybe a fun idea.

## Handle states and routes

> You understand how to manage states in your applications and inform the user about states where necessary.

- [ ] Routing & states can be managed with or without a micro library
- [ ] The user flow and object / class flow are visualized
- [ ] The interface contains feedback to the user when to wait for data to be loaded

### Tips

- There is no router yet, but thats logical. Start with using bundler, so you can prepare this and be one step ahead! 
- No user interface yet, can the user randomize the pictures, or remove them? Maybe a fun item to implement. 

# Repository 

- [x] Is there a repo description at the top?
- [x] Is the repo open to issues?
- [x] Does it include a .gitignore
- [x] Is the concept described well in the readme?
- [x] Is the API described in the readme?

### Tips

- Clear GitHub repository! Nice to see that you already have a UI-Design with the idea you want to create. The API is described perfectly with all the entry's, and the concept is clear to me. You have a .gitignore, maybe a tip to place the docs/ folder with the @CMDA information in the .gitignore, so you have a clean repository.
 
# Code 

- [x] Try to understand the code flow
- [x] Check the code against our course's best practices
- [x] Check the code for consistency, is code being written the same way in different places?
- [x] Does the code follow naming conventions? Do variable and function names make sense to you?

### Tips

- Good function chains, logical function and variable names! Maybe an idea to go fully ES6 and writing Arrow functions? Example: 

```js
const func = (param) => { console.log(param) }
const func = async (param) => { console.log(param) }
```

**Comment by lars-ruijs** [comment]
- Divided code into modules
- Created an Actor Diagram
- Integrated 'Routie' for routing
